### ISSUE TITLE
cant compile in  rustc 1.14.0-nightly (3f4408347 2016-10-27)

### ISSUE THREAD

**Issue by nextel** [jedisct1/rust-nats#2]
Hi, i eant to compile my app with your nats lib, in rustc 1.14.0-nightly (3f4408347 2016-10-27)
but i have porblems with dependence, cant u help me to fix it?

`  Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling serde_codegen_internals v0.4.0
   Compiling quasi v0.16.0
   Compiling aster v0.22.1
error[E0432]: unresolved import `syntax::ext::base::DummyMacroLoader`
 --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/mac.rs:3:25
  |
3 | use syntax::ext::base::{DummyMacroLoader, ExtCtxt};
  |                         ^^^^^^^^^^^^^^^^ no `DummyMacroLoader` in `syntax::ext::base`

error[E0433]: failed to resolve. Could not find `PathListItemKind` in `syntax::ast`
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/item.rs:426:44
    |
426 |         self.idents.push(respan(self.span, ast::PathListItemKind::Mod {
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `PathListItemKind` in `syntax::ast`

error[E0433]: failed to resolve. Could not find `PathListItemKind` in `syntax::ast`
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/item.rs:436:44
    |
436 |         self.idents.push(respan(self.span, ast::PathListItemKind::Ident {
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `PathListItemKind` in `syntax::ast`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:144:81
    |
144 |         panictry!(parse_tts_from_source_str("<quote expansion>".to_string(), s, cx.cfg(), cx.parse_sess()))
    |                                                                                 ^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:159:81
    |
159 |         panictry!(parse_tts_from_source_str("<quote expansion>".to_string(), s, cx.cfg(), cx.parse_sess()))
    |                                                                                 ^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:137:64
    |
137 |                         if let Ok((ser, de)) = get_renames(cx, meta_items) {
    |                                                                ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:158:73
    |
158 |                         if let Ok((ser, de)) = get_where_predicates(cx, meta_items) {
    |                                                                         ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:229:64
    |
229 |                         if let Ok((ser, de)) = get_renames(cx, meta_items) {
    |                                                                ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:318:64
    |
318 |                         if let Ok((ser, de)) = get_renames(cx, meta_items) {
    |                                                                ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:377:73
    |
377 |                         if let Ok((ser, de)) = get_where_predicates(cx, meta_items) {
    |                                                                         ^^^^^^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:347:13
    |
347 |             self.cfg(),
    |             ^^^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:355:13
    |
355 |             self.cfg(),
    |             ^^^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:363:13
    |
363 |             self.cfg(),
    |             ^^^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.16.0/src/lib.rs:371:13
    |
371 |             self.cfg(),
    |             ^^^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:510:18
    |
510 |             Some(items)
    |                  ^^^^^ expected slice, found struct `std::vec::Vec`
    |
    = note: expected type `&[syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>]`
    = note:    found type `&std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:590:9
    |
590 |         cx.cfg(),
    |         ^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen_internals-0.4.0/src/attr.rs:596:66
    |
596 |     let mut parser = parse::new_parser_from_tts(cx.parse_sess(), cx.cfg(), tts);
    |                                                                  ^^^^^^^^ expected struct `std::vec::Vec`, found reference
    |
    = note: expected type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`
    = note:    found type `&std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error: aborting due to 8 previous errors

Build failed, waiting for other jobs to finish...
error: aborting due to 6 previous errors

Build failed, waiting for other jobs to finish...
error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/attr.rs:249:73
    |
249 |         let item = respan(self.span, ast::MetaItemKind::List(self.name, self.items));
    |                                                                         ^^^^^^^^^^ expected struct `syntax::codemap::Spanned`, found struct `syntax::ptr::P`
    |
    = note: expected type `std::vec::Vec<syntax::codemap::Spanned<syntax::ast::NestedMetaItemKind>>`
    = note:    found type `std::vec::Vec<syntax::ptr::P<syntax::codemap::Spanned<syntax::ast::MetaItemKind>>>`

error[E0063]: missing field `is_shorthand` in initializer of `syntax::ast::Field`
    --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/expr.rs:1057:21
     |
1057 |         let field = ast::Field {
     |                     ^^^^^^^^^^ missing `is_shorthand`

error: no associated item named `None` found for type `syntax::ast::FunctionRetTy` in the current scope
  --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/fn_decl.rs:98:22
   |
98 |         let ret_ty = ast::FunctionRetTy::None(self.span);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0063]: missing field `span` in initializer of `syntax::ast::Generics`
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/generics.rs:214:30
    |
214 |         self.callback.invoke(ast::Generics {
    |                              ^^^^^^^^^^^^^ missing `span`

error[E0308]: mismatched types
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/item.rs:317:13
    |
317 |             self.constness,
    |             ^^^^^^^^^^^^^^ expected struct `syntax::codemap::Spanned`, found enum `syntax::ast::Constness`
    |
    = note: expected type `syntax::codemap::Spanned<syntax::ast::Constness>`
    = note:    found type `syntax::ast::Constness`

error[E0063]: missing field `attrs` in initializer of `syntax::ast::LifetimeDef`
  --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/lifetime.rs:43:9
   |
43 |         ast::LifetimeDef {
   |         ^^^^^^^^^^^^^^^^ missing `attrs`

error[E0063]: missing field `attrs` in initializer of `syntax::ast::LifetimeDef`
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/lifetime.rs:111:30
    |
111 |         self.callback.invoke(ast::LifetimeDef {
    |                              ^^^^^^^^^^^^^^^^ missing `attrs`

error[E0308]: mismatched types
  --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/method.rs:73:24
   |
73 |             constness: self.constness,
   |                        ^^^^^^^^^^^^^^ expected struct `syntax::codemap::Spanned`, found enum `syntax::ast::Constness`
   |
   = note: expected type `syntax::codemap::Spanned<syntax::ast::Constness>`
   = note:    found type `syntax::ast::Constness`

error: no associated item named `Vec` found for type `syntax::ast::TyKind` in the current scope
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/ty.rs:142:28
    |
142 |         self.build_ty_kind(ast::TyKind::Vec(ty))
    |                            ^^^^^^^^^^^^^^^^

error[E0063]: missing field `attrs` in initializer of `syntax::ast::TyParam`
   --> /home/nextel/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.22.1/src/ty_param.rs:103:30
    |
103 |         self.callback.invoke(ast::TyParam {
    |                              ^^^^^^^^^^^^ missing `attrs`

error: aborting due to 10 previous errors

error: Could not compile `serde_codegen_internals`.

To learn more, run the command again with --verbose.
`

**Comment by jedisct1** [comment]
Thanks for reporting this!

I just published a new version that should work out of the box, including on Rust-stable.

Thanks!
